In [1]:
# создание матриц
matrix(1:6, nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [2]:
# избавляемся от избыточности
matrix(1:6, nrow = 2)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [4]:
# упаковка по строкам
matrix(1:6, nrow = 2, byrow = T)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [6]:
# если вектор короче необходимого для размерности, то он будет переписан
matrix(7:8, nrow = 2, ncol = 5)

[,1] [,2] [,3] [,4] [,5]
[1,] 7    7    7    7    7   
[2,] 8    8    8    8    8

In [7]:
# атрибут dim отвечает за размерность

In [8]:
m <- matrix(1:6, nrow = 2, ncol = 3)

In [9]:
dim(m)

[1] 2 3

In [10]:
# или
c(nrow(m), ncol(m))

[1] 2 3

In [11]:
# превращаем матрицу в вектор, убирая атрибут dim
dim(m) <- NULL;m

[1] 1 2 3 4 5 6

In [12]:
is.matrix(m)

[1] FALSE

In [13]:
is.vector(m)

[1] TRUE

In [14]:
# восстанавливаем атрибут
dim(m) <- c(2, 3)

In [15]:
m

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [17]:
is.matrix(m)

[1] TRUE

In [18]:
is.vector(m)

[1] FALSE

In [19]:
# арифметические операции с матрицами

In [22]:
m1 <- matrix(1:4, nrow = 2)
m2 <- matrix(c(1, 2, 2, 3), nrow = 2)

In [23]:
m1; m2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 1    2   
[2,] 2    3

In [24]:
# поэлементное сложение матриц
m1 + m2

[,1] [,2]
[1,] 2    5   
[2,] 4    7

In [25]:
# добавляем к матрице число
m1 + 5

[,1] [,2]
[1,] 6    8   
[2,] 7    9

In [26]:
m1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [27]:
m1 * 5

[,1] [,2]
[1,]  5   15  
[2,] 10   20

In [28]:
m1 * m2

[,1] [,2]
[1,] 1     6  
[2,] 4    12

In [29]:
# умножение в линейной алгебре

In [30]:
m1 %*% m2

[,1] [,2]
[1,]  7   11  
[2,] 10   16

In [31]:
m1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [32]:
m2

[,1] [,2]
[1,] 1    2   
[2,] 2    3

In [33]:
# индексирование матрци

In [38]:
m <- matrix(1:10, ncol = 5); m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [40]:
m[1, 3]

[1] 5

In [41]:
m[2, 3]

[1] 6

In [43]:
# доступ к всей строке или к всему столбцу

In [44]:
m[2,]

[1]  2  4  6  8 10

In [45]:
m[,2]

[1] 3 4

In [46]:
# замена значений

In [48]:
m[1,] <- 0;m

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0     0  
[2,] 2    4    6    8    10

In [49]:
# перепривоить все столбцы кроме 5-го
m[, -5] <- 11:18;m

[,1] [,2] [,3] [,4] [,5]
[1,] 11   13   15   17    0  
[2,] 12   14   16   18   10

In [50]:
# схлопывание марицы

In [53]:
m <- matrix(1:10, ncol = 5)
ind <- c(1, 3, 5)
m[,ind]

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10

In [52]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [54]:
ind <- 3

In [57]:
# размерность схлапывается и мы получаем вектор
m[, ind]

[1] 5 6

In [56]:
# чтобы получить именно матрицу, а не вектор
m[, ind, drop = F]

[,1]
[1,] 5   
[2,] 6

In [58]:
# именованные матрицы

In [59]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [61]:
rownames(m) <- c("row1", "row2")
colnames(m) <- paste0('colum', 1:5)

In [62]:
m

colum1 colum2 colum3 colum4 colum5
row1 1      3      5      7       9    
row2 2      4      6      8      10

In [93]:
m["row1", c("colum2", "colum4"), drop = F]

colum2 colum4
row1 3      7

In [94]:
# присоединение матриц

In [101]:
cbind(m, m_copy)

colum1 colum2 colum3 colum4 colum5 colum1 colum2 colum3 colum4 colum5
row1 1      3      5      7       9     1      3      5      7       9    
row2 2      4      6      8      10     2      4      6      8      10

In [102]:
rbind(m, m_copy)

colum1 colum2 colum3 colum4 colum5
row1 1      3      5      7       9    
row2 2      4      6      8      10    
row1 1      3      5      7       9    
row2 2      4      6      8      10

In [106]:
# ...(ellipsis)

In [107]:
# это значит, что в функцию можно передавать неограниченное число объектов

In [108]:
cbind(m, m_copy, 1:2, c(5, 3), m_copy[, 1], m * 3, cbind(m, m_copy))

colum1 colum2 colum3 colum4 colum5 colum1 colum2 colum3 colum4 colum5 ...
row1 1      3      5      7       9     1      3      5      7       9     ...
row2 2      4      6      8      10     2      4      6      8      10     ...
     colum1 colum2 colum3 colum4 colum5 colum1 colum2 colum3 colum4 colum5
row1 1      3      5      7       9     1      3      5      7       9    
row2 2      4      6      8      10     2      4      6      8      10

In [109]:
# apply

In [110]:
f <- function(x) {
    sum(x^2)
}

In [112]:
m <- matrix(1:25, 5)

In [113]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [115]:
apply(m, 1, f)

[1]  855  970 1095 1230 1375

In [117]:
apply(m, 2, f)

[1]   55  330  855 1630 2655

In [121]:
# применение функции к каждому элементу

In [122]:
apply(m, 1:2, f)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    36  121  256  441 
[2,]  4    49  144  289  484 
[3,]  9    64  169  324  529 
[4,] 16    81  196  361  576 
[5,] 25   100  225  400  625

In [125]:
apply(m, 1:2, function(i) if (i > 13) i else 13)

[,1] [,2] [,3] [,4] [,5]
[1,] 13   13   13   16   21  
[2,] 13   13   13   17   22  
[3,] 13   13   13   18   23  
[4,] 13   13   14   19   24  
[5,] 13   13   15   20   25

In [127]:
# то же самое при помощи логического индексирования
m[m <= 13] <- 13;m

[,1] [,2] [,3] [,4] [,5]
[1,] 13   13   13   16   21  
[2,] 13   13   13   17   22  
[3,] 13   13   13   18   23  
[4,] 13   13   14   19   24  
[5,] 13   13   15   20   25

In [128]:
# наиболее частые операции

In [130]:
m <- matrix(1:25, 5)

In [131]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [136]:
rowSums(m)

[1] 55 60 65 70 75

In [137]:
colSums(m)

[1]  15  40  65  90 115

In [138]:
rowMeans(m)

[1] 11 12 13 14 15

In [139]:
all.equal(rowSums(m), apply(m, 1, sum))

[1] TRUE

In [141]:
all.equal(rowMeans(m), apply(m, 1, mean))

[1] TRUE

In [146]:
m[5, 5]

[1] 25

In [148]:
m1[2, 2]

[1] 4

In [216]:
find_closest <- function(v, n) {
    x <- abs(v - n)
    which(x == min(x))

}

In [217]:
v <- c(1, 1, 1, 1, 2, 3, 4, 5);v

[1] 1 1 1 1 2 3 4 5

In [218]:
n <- 1

In [219]:
find_closest(v, n)

[1] 1 2 3 4

In [211]:
min(abs(v - 1))

[1] 0

In [205]:
min(abs(v -1))

[1] 0

In [215]:
which(v == min(v))

[1] 1 2 3 4

In [2]:
# bind matrices diagonally
bind_diag <- function(m1, m2, fill) {
    m3 <- matrix(fill, nrow = nrow(m1) + nrow(m2),
                ncol = ncol(m1) + ncol(m2))
    m3[1:nrow(m1), 1:ncol(m1)] <- m1
    m3[nrow(m1) + 1:nrow(m2), ncol(m1) + 1:ncol(m2)] <- m2
    m3
}

In [3]:
m1 <- matrix(1:12, nrow = 3)
m2 <- matrix(10:15, ncol = 3)

In [4]:
m1

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [5]:
m2

[,1] [,2] [,3]
[1,] 10   12   14  
[2,] 11   13   15

In [27]:
bind_diag(m1, m2, fill = NA)

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  1    4    7   10   NA   NA   NA  
[2,]  2    5    8   11   NA   NA   NA  
[3,]  3    6    9   12   NA   NA   NA  
[4,] NA   NA   NA   NA   10   12   14  
[5,] NA   NA   NA   NA   11   13   15

In [209]:
build_ziggurat <- function(n) {
    fill = 1
    x <- matrix(fill, nrow = n + (n-1), ncol = n + (n - 1))
    if (n > 1) {
        for (i in 1:(n-1)) {
            x[i:(nrow(x)-(i-1)), i:(ncol(x)-(i-1))] <- i
            x[n,n] <- n
        }
    }else {
        x
    }
    x
}

In [212]:
system.time(build_ziggurat(1000))

   user  system elapsed 
 10.222   0.835  11.058 

In [185]:
x

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    1    1    1    1    1    1   
[2,] 1    2    2    2    2    2    1   
[3,] 1    3    3    3    3    2    1   
[4,] 1    3    3    4    3    2    1   
[5,] 1    3    3    3    3    2    1   
[6,] 1    2    2    2    2    2    1   
[7,] 1    1    1    1    1    1    1

In [213]:
3 + 3

[1] 6

In [214]:
# list

In [227]:
list(1:5, "my date", matrix(0, 2, 2))[1]

[[1]]
[1] 1 2 3 4 5

In [228]:
# список с именами
list(a =1, b = 1:3, "1to5" = 1:5, 42)

$a
[1] 1

$b
[1] 1 2 3

$`1to5`
[1] 1 2 3 4 5

[[4]]
[1] 42

In [229]:
# элементом списка может быть список
list(a = list(1, 2, 3), b = list(list(4), 5, 6))

$a
$a[[1]]
[1] 1

$a[[2]]
[1] 2

$a[[3]]
[1] 3


$b
$b[[1]]
$b[[1]][[1]]
[1] 4


$b[[2]]
[1] 5

$b[[3]]
[1] 6

In [230]:
# конкатенация списков
l1 <- list(name = "john", salary = 1000)
l2 <- list(has_car = T, car = "lamborgini")

In [231]:
l1

$name
[1] "john"

$salary
[1] 1000

In [232]:
l2

$has_car
[1] TRUE

$car
[1] "lamborgini"

In [233]:
# склеивание списков

In [234]:
c(l1, l2)

$name
[1] "john"

$salary
[1] 1000

$has_car
[1] TRUE

$car
[1] "lamborgini"

In [242]:
#вектор можно привести к списку
v <- 1:7
is.vector(list(v)[1])

[1] TRUE

In [244]:
is.list(list(v))

[1] TRUE

In [245]:
# конверсия в обратную сторону осмысленна не вссегда 

In [246]:
# но если она осмысленна, то есть unlist

In [256]:
l <- list(1:3, 4:5, last = 6)

In [249]:
unlist(l)

last 
   1    2    3    4    5    6

In [250]:
is.vector(unlist(l))

[1] TRUE

In [251]:
is.list(l)

[1] TRUE

In [252]:
# нужно помнить, что при приведении к ветору мы задействуем автоматическое приведение типов,
# так как вектор содержит элементы только одного типа данных

In [253]:
unlist(c(l, "spy"))

last       
  "1"   "2"   "3"   "4"   "5"   "6" "spy"

In [254]:
# доступ к элементам списка

In [257]:
l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

$last
[1] 6

In [258]:
l[3:2]

$last
[1] 6

[[2]]
[1] 4 5

In [259]:
l[-(1:2)]

$last
[1] 6

In [260]:
l[c(F, T, F)]

[[1]]
[1] 4 5

In [261]:
l["last"]

$last
[1] 6

In [277]:
# при обращении к единичному элементу получаем все равно список длины 1

In [263]:
is.list(l["last"])

[1] TRUE

In [265]:
# обращение к конкретному элементу списка

In [274]:
l[[1]]

[1] 1 2 3

In [275]:
is.vector(l[[1]])

[1] TRUE

In [276]:
is.list(l[[1]])

[1] FALSE

In [278]:
# доступ по имени с частичным дополнением

In [284]:
# получим сам элемент, а не подсписок

In [286]:
l$last

[1] 6

In [285]:
is.vector(l$last)

[1] TRUE

In [287]:
# в этом способе не обязательно указывать полное имя

In [293]:
l$las

[1] 6

In [294]:
# замена и добавление элементов списка

In [303]:
l <- list(1:3, 4:5, last = 6)

In [302]:
l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

In [304]:
l[[3]] <- NULL;l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

In [305]:
l[[4]] <- 99;l

[[1]]
[1] 1 2 3

[[2]]
[1] 4 5

[[3]]
NULL

[[4]]
[1] 99

In [306]:
l <- list(vec = 1:7, fun = sqrt) #l$fun(4)
names(l)

[1] "vec" "fun"

In [307]:
l

$vec
[1] 1 2 3 4 5 6 7

$fun
function (x)  .Primitive("sqrt")

In [309]:
l$fun(16)

[1] 4

In [311]:
is.null(l$string)

[1] TRUE

In [312]:
l$string <- "Citius, altius, fortius"

In [313]:
l

$vec
[1] 1 2 3 4 5 6 7

$fun
function (x)  .Primitive("sqrt")

$string
[1] "Citius, altius, fortius"

In [314]:
is.null(l$string)

[1] FALSE

In [315]:
l$fun(625)

[1] 25

In [316]:
# применеие функции к каждому элементу списка

In [317]:
l <- list(a = c("12", "34"), b = LETTERS[5:10], c = 1:5)

In [318]:
l

$a
[1] "12" "34"

$b
[1] "E" "F" "G" "H" "I" "J"

$c
[1] 1 2 3 4 5

In [319]:
# узнать длину каждого элемента
lapply(l, length)

$a
[1] 2

$b
[1] 6

$c
[1] 5

In [326]:
l

$a
[1] "12" "34"

$b
[1] "E" "F" "G" "H" "I" "J"

$c
[1] 1 2 3 4 5

In [323]:
# добавление аргумента в функцию
lapply(l, paste, collapse = "-")

$a
[1] "12-34"

$b
[1] "E-F-G-H-I-J"

$c
[1] "1-2-3-4-5"

In [324]:
# то же самое при помощи анонимной функции
lapply(l, function(s) paste(s, collapse = "|"))

$a
[1] "12|34"

$b
[1] "E|F|G|H|I|J"

$c
[1] "1|2|3|4|5"

In [328]:
# дополнительное упрощение и получение вектора на выходе (sapply - simpify apply)
sapply(l, paste, collapse = "|")

a             b             c 
      "12|34" "E|F|G|H|I|J"   "1|2|3|4|5"

In [329]:
l <- list(some_name = 1, incredibly_long_name = 2)
l

$some_name
[1] 1

$incredibly_long_name
[1] 2

In [332]:
l$inc + 1

[1] 3

In [336]:
# это удобно при длинных названиях

In [337]:
# для функций это тоже работает

In [338]:
f <- function(x, ridiculously_long_arg) {
    x + ridiculously_long_arg
}

In [342]:
f(3, ridic = 10)

[1] 13

In [361]:
# Глоссарий

# ?matrix
# ?dim, ?rownames, ?colnames
# ?rbind, ?cbind, ?apply
# ?rowSums, ?rowMeans, ?colSums, ?colMeans
# ?list, ?unlist
# ?"[" (?"[[", ?"$")
# ?lapply, ?sapply 
# ?"..."(ellipsis)

In [362]:
# в R есть три похожих ключевых слова, NA, NaN и NULL. Они различаются по смысловой нагрузке. 

# NA -- это пропущенное значение ("not available").
# Например, респондент не ответил на все вопросы предложенной анкеты,
# или данные с метеостанции за определённый период потерялись из-за сбоя оборудования.
# NA в этом случае обозначает, что эти данные существуют и имеют смысл, но их не удалось узнать.

# NaN -- "not-a-number" -- результат недопустимой арифметической операции, например 0/0 или Inf - Inf.

# NULL -- отсутствие объекта, "пустота".
# Применяется в тех случаях, когда объект действительно не существует,
# не может иметь осмысленного значения.

# Для проверки значений есть три функции, is.na, is.nan и is.null, соответственно.

In [379]:
x <- matrix(2, 2, 2);x

[,1] [,2]
[1,] 2    2   
[2,] 2    2

In [386]:
diag(4)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

In [384]:
diag(c(1, 2, 3))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [387]:
# get the longest element
get_longest <- function(l) {
    len <- sapply(l, length)
    ind <- which.max(len)
    list(number = ind, element = l[[ind]])
}

In [391]:
v1 <- c(1, 2, 3)
v2 <- c(95, 96, 97, 98)
l <- list(v1, v2)

In [390]:
get_longest(list(v1, v2))

$number
[1] 2

$element
[1] 95 96 97 98

In [392]:
len <- sapply(l, length)

In [393]:
len

[1] 3 4

In [394]:
ind <- which.max(len);ind

[1] 2

In [443]:
# generate list with random length and contents
gen_list <- function (n_elements, max_len, seed = 111) {
    set.seed(seed)
    len <- sample(1:max_len, n_elements)
    lapply(1:n_elements, function(i){
        rnorm(len[i])
    })
}

In [446]:
l1 <- gen_list(4, 10);l1

[[1]]
[1] -2.3023457 -0.1708760  0.1402782 -1.4974267

[[2]]
[1] -1.0101884 -0.9484756 -0.4939622

[[3]]
[1] -0.17367413 -0.40659878  1.84563626  0.39405411  0.79752850 -1.56666536
[7] -0.08585101

[[4]]
[1] -0.3591395

In [448]:
gl1 <- get_longest(l1);gl1

$number
[1] 3

$element
[1] -0.17367413 -0.40659878  1.84563626  0.39405411  0.79752850 -1.56666536
[7] -0.08585101

In [449]:
l2 <- gen_list(4, 10, 777);l2

[[1]]
[1]  0.5108363 -0.3988121  1.6386861  0.6212740  0.2027043  1.1089378 -0.2062248
[8] -0.3789650

[[2]]
[1] -0.3042617

[[3]]
[1]  0.05416232 -1.88093062

[[4]]
[1] -0.03375647  2.31149476  0.97234017  0.96460804

In [450]:
get_longest(l2)

$number
[1] 1

$element
[1]  0.5108363 -0.3988121  1.6386861  0.6212740  0.2027043  1.1089378 -0.2062248
[8] -0.3789650

In [558]:
v <- c(5, 2, 7, 7, 7, 2, 0, 0)

In [559]:
t <- table(v)

In [560]:
t

v
0 2 5 7 
2 2 1 3 

In [561]:
df <- data.frame(t)

In [562]:
df

v Freq
1 0 2   
2 2 2   
3 5 1   
4 7 3

In [563]:
df[2]

Freq
1 2   
2 2   
3 1   
4 3

In [578]:
v1 <- as.integer(as.vector(df$v))

In [579]:
v1

[1] 0 2 5 7

In [556]:
v2 <- df$Freq;v2

[1] 3 2 2 2 2

In [557]:
matrix(c(v1, v2), byrow = T, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 3    2    2    2    2

In [585]:
count_elements <- function(x) {
    df <- data.frame(table(x))
    v1 <- as.vector((df$x))
    v2 <- df$Freq
    matrix(c(v1, v2), nrow = 2, byrow = T)

}


In [596]:
count_elements(v)

[,1] [,2] [,3] [,4]
[1,] 0    2    5    7   
[2,] 2    2    1    3

In [594]:
count_elements <- function(x) {
    t <- table(x)
    matrix(rbind(as.numeric(names(t)), t), nrow = 2)

}


In [595]:
count_elements <- function(x) {
rbind(sort(unique(x)), sapply(sort(unique(x)), function(i) length(x[x==i])))
}

In [598]:
v <- rep(c(0, 1 ,2), each = 4)

In [600]:
m <- matrix(v, 3, 4)

In [601]:
m

[,1] [,2] [,3] [,4]
[1,] 0    0    1    2   
[2,] 0    1    1    2   
[3,] 0    1    2    2

In [602]:
m[m== 0] <- NA

In [603]:
m

[,1] [,2] [,3] [,4]
[1,] NA   NA   1    2   
[2,] NA    1   1    2   
[3,] NA    1   2    2

In [604]:
set.seed(1789)
bastille <- list(
  "La Chapelle Tower" = rbinom(5, 10, 1/2), 
  "Tresor Tower" = rbinom(8, 12, 1/4), 
  "Comte Tower" = rbinom(14, 3, 1/5) + 1,
  "Baziniere Tower" = rbinom(8, 4, 4/5), 
  "Bertaudiere Tower" = rbinom(4, 8, 2/3),
  "Liberte Tower" = rbinom(1, 100, 0.1), 
  "Puits Tower" = rbinom(5, 5, 0.7),
  "Coin Tower" = rbinom(3, 16, 0.4)
)

In [635]:
v1 <- sapply(bastille, sum); v1

La Chapelle Tower      Tresor Tower       Comte Tower   Baziniere Tower 
               28                30                23                24 
Bertaudiere Tower     Liberte Tower       Puits Tower        Coin Tower 
               18                10                20                17

In [658]:
paste(names(which.min(v1)), min(v1), sum(v1), sep = ", ")

[1] "Liberte Tower, 10, 170"

In [659]:
# Общий глоссарий для этого урока:

# ?matrix
# ?dim, ?rownames, ?colnames
# ?rbind, ?cbind, ?apply
# ?rowSums, ?rowMeans, ?colSums, ?colMeans
# ?list, ?unlist
# ?"[" (?"[[", ?"$")
# ?lapply, ?sapply
# Partial matching, ?"..." (ellipsis)
# ?diag